import nodemailer from 'nodemailer';
import type { SummarizedArticle } from './summarizer.js';

const CATEGORY_LABEL: Record<SummarizedArticle['category'], string> = {
  XRP:    'XRP / Ripple',
  Crypto: '暗号資産 / ブロックチェーン',
  AI:     '人工知能 (AI)',
  Tech:   'テクノロジー全般',
};

const CATEGORY_COLOR: Record<SummarizedArticle['category'], string> = {
  XRP:    '#1a73e8',
  Crypto: '#f7931a',
  AI:     '#7c3aed',
  Tech:   '#10b981',
};

function escapeHtml(s: string): string {
  return s.replace(/[&<>"']/g, (c) =>
    ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]!)
  );
}

export function buildHtml(buckets: Record<SummarizedArticle['category'], SummarizedArticle[]>): string {
  const today = new Date().toLocaleDateString('ja-JP', {
    timeZone: 'Asia/Tokyo',
    year: 'numeric',
    month: 'long',
    day: 'numeric',
    weekday: 'short',
  });

  const sections = (Object.keys(buckets) as SummarizedArticle['category'][])
    .filter((k) => buckets[k].length > 0)
    .map((k) => {
      const items = buckets[k]
        .map(
          (a) => `
        <li style="margin-bottom:18px;">
          <a href="${escapeHtml(a.link)}" style="color:#1a73e8;text-decoration:none;font-weight:600;font-size:15px;">
            ${escapeHtml(a.title)}
          </a>
          <div style="color:#888;font-size:12px;margin:2px 0 6px;">
            ${escapeHtml(a.source)} &middot; ${a.pubDate.toLocaleString('ja-JP', { timeZone: 'Asia/Tokyo' })}
          </div>
          <div style="color:#333;font-size:14px;line-height:1.7;">${escapeHtml(a.jpSummary)}</div>
        </li>`
        )
        .join('');

      return `
      <h2 style="border-left:4px solid ${CATEGORY_COLOR[k]};padding-left:10px;color:#222;font-size:18px;margin-top:32px;">
        ${CATEGORY_LABEL[k]}
        <span style="color:#aaa;font-size:13px;font-weight:normal;">(${buckets[k].length}件)</span>
      </h2>
      <ul style="list-style:none;padding-left:0;">${items}</ul>`;
    })
    .join('');

  return `<!DOCTYPE html>
<html lang="ja">
<body style="font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Helvetica,Arial,sans-serif;max-width:680px;margin:0 auto;padding:20px;background:#f5f5f5;color:#222;">
  <div style="background:#fff;padding:28px 32px;border-radius:10px;box-shadow:0 1px 4px rgba(0,0,0,0.07);">
    <h1 style="margin:0 0 4px;font-size:22px;color:#111;">📰 Daily Tech &amp; Crypto Digest</h1>
    <div style="color:#888;font-size:13px;margin-bottom:4px;">${today} &nbsp;・&nbsp; 過去24時間の海外一次情報まとめ</div>
    ${sections || '<p style="color:#aaa;margin-top:24px;">本日は対象記事が見つかりませんでした。</p>'}
    <hr style="margin-top:36px;border:none;border-top:1px solid #eee;">
    <p style="color:#bbb;font-size:11px;margin:12px 0 0;">Generated by daily-news-bot &nbsp;・&nbsp; Powered by Google Gemini</p>
  </div>
</body>
</html>`;
}

export async function sendMail(html: string): Promise<void> {
  const { GMAIL_USER, GMAIL_APP_PASSWORD, MAIL_TO } = process.env;
  if (!GMAIL_USER || !GMAIL_APP_PASSWORD || !MAIL_TO) {
    throw new Error('Mail env vars (GMAIL_USER / GMAIL_APP_PASSWORD / MAIL_TO) are not set');
  }

  const transporter = nodemailer.createTransport({
    service: 'gmail',
    auth: { user: GMAIL_USER, pass: GMAIL_APP_PASSWORD },
  });

  const today = new Date().toLocaleDateString('ja-JP', { timeZone: 'Asia/Tokyo' });

  await transporter.sendMail({
    from: `"Daily News Bot" <${GMAIL_USER}>`,
    to: MAIL_TO,
    subject: `📰 [${today}] 朝のテック&クリプト要約`,
    html,
  });

  console.log(`[mailer] Sent to ${MAIL_TO}`);
}
